# Create image from nodejs base image
FROM node:6

# Clone the repo from github
RUN git clone https://github.com/ronniebnorth/TabTracker

# Change workind directory to the cloned repo
WORKDIR /TabTracker/client

# Install all the dependencies
RUN npm install

# Expose port
EXPOSE 80

# Run the application
CMD ["npm", "start"]

# Change workind directory to the cloned repo
WORKDIR /TabTracker/server

# Install all the dependencies
RUN npm install

# Expose port
EXPOSE 8081

# Run the application
CMD ["npm", "start"]